name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on:
      ubuntu-latest
    steps:
      - name: Clones the repository
        run: actions/checkout@v4.1.1
      - name: Roda outro comando
        run: echo $(ls)
