name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on:
      ubuntu-latest
    steps:
      - name: Clones the repository
        uses: actions/checkout@v4
      - name: Roda outro comando
        run: echo $(ls)
